baseURL: 'https://pestpolicy.com/'
languageCode: 'en-us'
title: 'Pest Policy Insights'
theme: 'hugo-PaperMod'

outputs:
  home: ['HTML', 'RSS', 'JSON', 'sitemap']

params:
  env: 'production'
  defaultTheme: 'auto'
  title: "Pest Policy Insights"
  description: "Your comprehensive resource for pest control policies, tips, and information."
  robots: "index, follow"

  # Display settings
  showPostNav: true
  showBreadCrumbs: true
  showReadingTime: true
  showWordCount: true
  showCodeCopy: true

  # Homepage configuration
  homeInfoParams:
    title: "Recent Posts"
    content: "Latest updates from our blog"

  # hugo-PaperMod specific SEO parameters (check theme docs)
  siteLogo: "/images/logo.png"
  defaultOgImage: "/images/share.png"
  twitterSite: "@yourtwitterhandle"
  twitterCreator: "@yourtwitterhandle"
  # enableSchemaOrg: true

taxonomies:
  tag: 'tags'
  category: 'categories'

permalinks:
  posts: "/:slug/"

slug:
  ugly: false

frontmatter:
  url: ["permalink"]

build:
  errorOnMissingPagePermalinks: true
  errorOnInvalidPermalinks: true