baseURL: "https://pestpolicy.com/"
languageCode: "en-us"
title: 'Pest Policy Insights'
theme: 'hugo-PaperMod'

outputs:
  home:
    - "html"
    - "rss"
    - "json"
  page:
    - "html"
  section:
    - "html"
    - "rss"
  sitemap:
    - "xml" # Use the built-in "xml" format

outputFormats:
  xml:
    name: "Sitemap"
    mediaType: "application/xml"
    baseName: "sitemap"
    isHTML: false
    noUgly: true

# Remove any custom sitemap_full configurations

params:
  env: 'production'
  defaultTheme: 'auto'
  title: "Pest Policy Insights"
  description: "Your comprehensive resource for pest control policies, tips, and information."
  robots: "index, follow"

  # Any PaperMod specific sitemap configurations would go here
  # Consult the theme's documentation

taxonomies:
  tag: 'tags'
  category: 'categories'

permalinks:
  posts: "/:slug/"

slug:
  ugly: false

frontmatter:
  url: ["permalink"]

build:
  errorOnMissingPagePermalinks: true
  errorOnInvalidPermalinks: true